### ISSUE TITLE
Help with setup

### ISSUE THREAD

**Issue by ritam749** [dshukertjr/spot#17]
Hey i am new to Supabase. I love your project and want to improve on it. Could you please provide a very detail doc or video as I could understand it better . The doc or vid should contain stuff like columns adding,add code etc. Overall a comprehensive to setup the spot. PLEASE REPLY AS IT WOULD BE REALLY HELPFULL FOR COLEEGE PROJECT

**Comment by dshukertjr** [comment]
Hi @ritam749 !

I am so glad that you like this app! Yeah, detailed doc of how to get started is definitely something I would have to work on. In the mean while, I have created a video explaining how to get started with it. I hope it helps, but please don't hesitate to let me know if anything is unclear! I hope you ace your college project 🚀🚀🚀

The quality is not great, because I am using the free version of loom, but I hope it's good enough!
https://www.loom.com/share/60e23d1fb61b443eb10743bc71877471

**Comment by ritam749** [comment]
Than You Very Much!

**Comment by dshukertjr** [comment]
@ritam749 
I had totally forgotten about google map API keys and Firebase. 

You can change the google map's API key on Android [here](https://github.com/dshukertjr/spot/blob/f6420031fd46d5845a7e9fb337b58fcb8271b986/android/app/src/main/AndroidManifest.xml#L44) and iOS [here](https://github.com/dshukertjr/spot/blob/f6420031fd46d5845a7e9fb337b58fcb8271b986/ios/Runner/AppDelegate.swift#L11). 

Talking about Firebase, this project only uses Firebase for analytics at this point, so having to configure the correct firebase project is not necessary for running the app, but if you want to hook up your own Firebase project, you should be able to do so by replacing [this file](https://github.com/dshukertjr/spot/tree/main/ios/config/development) for iOS and [this file](https://github.com/dshukertjr/spot/tree/main/android/app/src/development) for Android. 

Changing those two files should be good enough to run it locally. This app is using flavors, and the description above is how to change firebase project connected to the development flavor. You can read more about flavors [here](https://medium.com/@animeshjain/build-flavors-in-flutter-android-and-ios-with-different-firebase-projects-per-flavor-27c5c5dac10b), but if you want to change the production flavor as well, you will need to swap [this file for iOS](https://github.com/dshukertjr/spot/tree/main/ios/config/production) and [this file for Android](https://github.com/dshukertjr/spot/blob/main/ios/config/production/GoogleService-Info.plist).

**Comment by ritam749** [comment]
Hey just just another question which api in google map console should i use. There are many such as geolocation, maps sdk ,roads api etc.

**Comment by dshukertjr** [comment]
@ritam749 
I am using the following APIs!
<img width="501" alt="Screen Shot 2021-06-13 at 14 03 11" src="https://user-images.githubusercontent.com/18113850/121795939-1a8f9700-cc50-11eb-9ba9-60df28abcca7.png">

**Comment by ritam749** [comment]
@dshukertjr 
sorry for troubling you again, I just want to know if you know can help me with me some **super base** flutter resources to get started. Such as videos on YouTube or website etc. Actually I wanted to create a logout button but could not find many resources to help. It would be helpful if you could tell me some resources which helped you so I can improve upon the project

**Comment by dshukertjr** [comment]
Hey @ritam749 !

Great point. While there are some of videos and articles out there that talk about using Supabase inside a Flutter project, I like to stick to the original source, that is the official Supabase documentation that you can find [here](https://supabase.io/docs/reference/javascript/supabase-client). While this documentation only covers the JavaScript SDK of Supabase, the syntax for everything in it is very similar in Dart SDK as well, so you will most likely be able to guess how to write it in Dart. 

If you get stuck with anything, you can always reach out to me or to the [Supabase community](https://github.com/supabase/supabase/discussions)!

**Comment by ritam749** [comment]
@dshukertjr 
I am really sorry for troubling you again and again. Some how when I am changing the production bundle id(which you have written above), and changing the firebase project and google maps api for both development and production flavor, I get a million errors. It's so big I can't even paste the whole thing in GitHub . It would be helpful if you could make a video or md file to help out. Showing how to do the above things from the start such as google map api in cloud developer platform and firebase from console up to configuring them in the project. Actually I don't use flavors much that's why it is getting confusing. Sorry for troubling you again and again. Actually I want to ace the college project, and find your project as the perfect base to improve upon to impress them.

**Comment by dshukertjr** [comment]
@ritam749 
Sure, I can make a video! I am a bit busy today, so it might be tomorrow, but would that be okay? 

Also, is this for Android only, or do you want to do iOS as well? I strongly recommend to sticking to Android only as iOS tend to have so much errors in general with Flutter and Firebase. In addition to that, which version of Flutter are you using on your computer?

> Actually I don't use flavors much that's why it is getting confusing.

Yeah, this is normal. Flavors are confusing and only necessary when you are building multiple environments. I get confused a lot as well lol

**Comment by ritam749** [comment]
I am using android

**Comment by ritam749** [comment]
yeah tomorrow is okay

**Comment by ritam749** [comment]
Yes! tomorrow is okay! Thank you again.

My OS is windows so I would want it for android only. My flutter version is:
`Flutter 2.2.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d79295af24 (3 days ago) • 2021-06-11 08:56:01 -0700
Engine • revision 91c9fc8fe0
Tools • Dart 2.13.3`

**Comment by dshukertjr** [comment]
I am so sorry for the delay @ritam749 !

Here are the videos explaining how to hook up your own firebase project and google map key for Spot. I am using a free version of loom (video capturing tool), which allows 5 min videos at max, so I had to break it into 3 videos, but hopefully this helps you! Let me know if you still see any errors or if I am missing anything. 

https://www.loom.com/share/c14a9389a8a04829b618331a3ad4e100
https://www.loom.com/share/ede5d7d979a74aa59b9ccec65bdf2a92
https://www.loom.com/share/f9546c54e74441e693a72ec78d9b1db7

**Comment by ritam749** [comment]
Thank you!

**Comment by dshukertjr** [comment]
@ritam749 No problem! I'm going to close this issue, but please feel free to reopen it any time you need help!
