### ISSUE TITLE
Google map integration

### ISSUE THREAD

**Issue by ritam749** [dshukertjr/spot#18]
I am very thankful for you making a video to help me with supabase. Just one more question, where do i put google map api key and are there other api keys i need to put. And is there anythong else i need to use to make this work as my own project, to show to the teachers. Thank you in advance

**Comment by ritam749** [comment]
Sorry for troubling you again but could you tell me if firebase is used and if yes what all do we have to enable in my firebase proj etc

**Comment by dshukertjr** [comment]
Hey @ritam749 

No problem at all! I had totally forgot about google map API key and Firebase 🤣 Thanks for pointing out. Let's move this to #17 and continue talking there!
