### ISSUE TITLE
Error while sign up

### ISSUE THREAD

**Issue by ritam749** [dshukertjr/spot#19]
Whenever i press signup button in the app it shows a error in both your and mine supabase projects
The error is(image provided below)
![2021-06-12 (6)](https://user-images.githubusercontent.com/72182707/121779581-15800880-cbba-11eb-8514-79f0157b8be0.png)

Another error in signin page
![2021-06-12 (5)](https://user-images.githubusercontent.com/72182707/121779611-36e0f480-cbba-11eb-847b-2aa1f64c54cf.png)

Sorry for continuously troubling you

**Comment by dshukertjr** [comment]
Thanks for opening an issue @ritam749 !

This error looks like the Supabase URL has not been configured. Are you running this on Android Studio? In that case, I suggest using VS code. On VS Code it should run without any issues. 

Spot relies on dart defined variables to run. The command to run Spot is something like this:
```
flutter run --flavor development --target lib/main_production.dart --dart-define=SUPABASE_URL=${{ secrets.SUPABASE_URL }} --dart-define=SUPABASE_ANNON_KEY=${{ secrets.SUPABASE_ANNON_KEY }}
```
With VS code, all of the configuration is set [here](https://github.com/dshukertjr/spot/tree/main/.vscode), so you should be able to run it with no additional configuration. I have no idea how to set up the same configuration on Android Studio, but I think there is a way to do it.

**Comment by ritam749** [comment]
Thank you for your answer, just one more question whenever I create a account on my emulator i get an error saying "Error sending confirmation mail ". Is this an error because i am using emulator  or only a error for me

**Comment by dshukertjr** [comment]
@ritam749 
Right, I had forgotten about this setting as well. Right now in Spot, I am not sending out confirmation emails, so I have it disabled like this. This should remove the error you are experiencing!
<img width="1369" alt="Screen Shot 2021-06-13 at 14 00 12" src="https://user-images.githubusercontent.com/18113850/121795871-af45c500-cc4f-11eb-8221-3b7f0317815d.png">

**Comment by dshukertjr** [comment]
I will go ahead and close this issue! Feel free to reopen it if it persists!

**Comment by taesai** [comment]
@dshukertjr 
Hello,
Same trouble here... whatever the flavor i run: No Host Specified in URI.
Nevertheless, it s an awesome project!
