### ISSUE TITLE
Schema Syntax Error

### ISSUE THREAD

**Issue by jtkeyva** [dshukertjr/spot#47]
I'm getting this when pasting in your query:

syntax error at or near ")"

It' highlighting the error at line 88. Any help appreciated.
Thanks

**Comment by dshukertjr** [comment]
Thank you so much @jtkeyva for reporting this!

There was an extra comma in the follow table declaration. I have fixed it now! Could you try running it again?

**Comment by jtkeyva** [comment]
@dshukertjr SQL ran with Success confirmation. Thanks for the speedy reply :)

**Comment by dshukertjr** [comment]
My pleasure!
