### ISSUE TITLE
Not working with my Supabase Credentials

### ISSUE THREAD

**Issue by jtkeyva** [dshukertjr/spot#48]
When I run the app using my Supabase credentials, the Profile tab does nothing, therefore I can't create a new account or log in. I made a tab that links directly to the login_page and I was able to create an account and update my profile. But then it was just stuck.

I restarted the app and profile tab still broken, but was able to make a video. The database entry worked and the files got uploaded but then I couldn't view them in the app. Just getting lot's of random errors and exceptions. I can't quite pinpoint it. 

I tried to record another video and It recorded but then when I went to save it I got an exception:
Invalid statusCode: 400

Changed back to your Supabase credentials and all works well.

To confirm, the steps are:

Supabase:
Enable GIS extensions
Disable Enable Email Confirmations
Run your provided SQL

Flutter:
Clone the spot repo
Open launch.json and change to my Supabase settings
SUPABASE_URL (My Supabase Config URL)
SUPABASE_ANNON_KEY  (My Supabase Project Key anon/public)
Run/Debug

Is there anything I'm missing??

Thanks

**Comment by jtkeyva** [comment]
I'm getting this as well:

[log] type 'Null' is not a subtype of type 'List<int>' in type cast
[log] #0      Stream.drain (dart:async/stream.dart:1093:33)
#1      NetworkImage._loadAsync
package:flutter/…/painting/_network_image_io.dart:99
        <asynchronous suspension>

UPDATE:
Looks like the token is not getting appended to the end of the file names in the database

**Comment by dshukertjr** [comment]
Hi @jtkeyva !

One step that is missing from the readme that I noticed is to turn email confirmation off. 
<img width="1351" alt="Screen Shot 2021-09-16 at 20 24 03" src="https://user-images.githubusercontent.com/18113850/133603787-97398d89-d9ad-4d6d-8d4a-650a79866c0e.png">

>Looks like the token is not getting appended to the end of the file names in the database

This reminded me of another thing that was missing from the `readme.md` is to make the buckets public. Could you try to run these queries to make the buckets public?

```sql
update storage.buckets set public = true where id = 'videos';
update storage.buckets set public = true where id = 'profiles';
```

Thank you for poking holes in this repo. It is very helpful!

**Comment by jtkeyva** [comment]
Thanks for the quick reply!
Yes, that query seemed to fix most things. Still having some issues with signing in & viewing profile page. I made a logout button but seems i need to restart app before being able to log in or logs out. Seems to be some state issues or token issues going on?

I'll be playing around with it now that I can add content. I'll report any patterns I find that could be causing problems.

**Comment by dshukertjr** [comment]
Good to know that at least something got fixed. I will share anything that I can find on my end as well!
